# Site settings
title: Baby Formula Free for All

author: Laura J. Forman
url: "http://single-jekyll-story.github.io" # the base hostname & protocol for your site
email: ljlandry@gmail.com
linkedin_full_url: https://www.linkedin.com/pub/laura-forman/7/719/5a5
twitter_username: doubleljsquared
github_repo:  babyformulaads/babyformulaads.github.io


baseurl: "" # the subpath of your site, e.g. /blog/, if applicable


# Build settings
markdown: kramdown
sass:
    sass_dir: assets/_sass



