# Site settings
title: The Baby Formula Mixup
description: |
  A story description that will show up at the top of the page on the front page.

author: Laura Forman
url: "http://single-jekyll-story.github.io" # the base hostname & protocol for your site
email: your-email@domain.com
linkedin_full_url: https://www.linkedin.com/in/demoaccount
twitter_username: jekyllrb
github_repo:  babyformulaads/babyformulaads.github.io


baseurl: "" # the subpath of your site, e.g. /blog/, if applicable


# Build settings
markdown: kramdown
sass:
    sass_dir: assets/_sass



